//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by spload.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME7                  128
#define IDR_SPLOADTYPE                  129
#define IDR_CONTEXTMENU                 130
#define IDR_MAINFRAME2                  130
#define IDR_MAINFRAME1                  131
#define IDB_BITMAP1                     131
#define IDB_BITMAP2                     133
#define IDB_BITMAP3                     137
#define IDB_DELBOX1                     138
#define IDB_DELBOX2                     139
#define IDB_DOWNBOX1                    140
#define IDB_DOWNBOX2                    141
#define IDB_UPBOX1                      142
#define IDB_UPBOX2                      143
#define IDB_SAVEBOX1                    144
#define IDB_SAVEBOX2                    145
#define IDB_SAVEBOX3                    146
#define IDB_SAVEBOX4                    147
#define IDI_TRAY                        148
#define IDR_TRAYMENU                    149
#define IDD_URLDIALOG                   150
#define IDR_CONTEXTMENU_UNSEL           151
#define IDB_BITMAP4                     153
#define IDB_BITMAP5                     155
#define IDB_TOOLBARBITMAP               156
#define IDI_HANDICON                    157
#define IDR_MAINFRAME3                  158
#define IDB_BITMAPADDURL                160
#define IDB_OSBITMAP                    162
#define IDB_BITMAP6                     165
#define IDB_GONORM                      167
#define IDB_GOFOCUS                     168
#define IDR_TOOLBAR1                    173
#define IDR_MAINFRAME4                  174
#define IDR_MAINFRAME5                  175
#define IDR_MAINFRAME6                  176
#define IDB_BITMAP7                     177
#define IDI_ICONBROWSER                 178
#define IDI_ICONSM                      179
#define ID_CONTEXTMENU_CLEARERROR       180
#define IDR_MAINFRAME8                  180
#define IDC_EDIT1                       1000
#define ID_BUTTONDOWNLOAD               32771
#define ID_BUTTONPAUSE                  32772
#define ID_CONTEXTMENU_DELETE           32773
#define ID_CONTEXTMENU_MOVEUP           32774
#define ID_CONTEXTMENU_MOVEDOWN         32775
#define ID_CONTEXTMENU_SAVETO           32776
#define ID_BUTTONFORCESTOP              32777
#define ID_FILE_STARTDOWNLOAD           32778
#define ID_FILE_STOPDOWNLOAD            32779
#define ID_HELP_CONTENTS                32780
#define ID_FILE_REMOVEALLITEMS          32781
#define ID_FILE_SHOWDOWNLOADFOLDER      32782
#define ID_TRAY_RESTORE                 32783
#define ID_FILE_ADDURL                  32784
#define ID_VIEW_ADDRESSBAR              32790
#define ID_HELP_CONNECTFUSIONWEBSITE    32791
#define ID_HELP_CONNECTFUSIONFAQ        32792
#define ID_HELP_CONNECTFUSIONSOURCE     32793
#define ID_FILE_STARTDOWNLOAD1          32794
#define ID_FILE_STOPDOWNLOAD1           32795
#define ID_BUTTONGO                     32796
#define ID_BUTTON32798                  32798
#define ID_FILE_SETDOWNLOADFOLDER       32799
#define IDS_ADDRESS                     61446
#define IDS_READY                       61447
#define IDS_SPEEDLOAD                   61448
#define IDS_SAVE                        61449
#define IDS_DOWNLOAD                    61450
#define IDS_STOP                        61451
#define IDS_CDINC                       61452
#define IDS_STATSTR                     61453
#define IDS_DOWNLOADSTOPPED             61454
#define IDS_STARTRESUME                 61455
#define IDS_STOPDOWNLOAD                61456
#define IDS_CLICKTOSCROLL               61457
#define IDS_DRAGDEST                    61458
#define IDS_DELETEDOWNLOAD              61459
#define IDS_MOVEDOWN                    61460
#define IDS_MOVEUP                      61461
#define IDS_SAVEDOWNLOADAS              61462
#define IDS_DELMSG                      61463
#define IDS_DELCONFIRM                  61464
#define IDS_SAVETO                      61465
#define IDS_STATUSS                     61466
#define IDS_PENDING                     61467
#define IDS_COMPLETED                   61468
#define IDS_PERCENT                     61469
#define IDS_STATFORMAT                  61470
#define IDS_ERRORS                      61471
#define IDS_UNABLETOLOAD                61472
#define IDS_PARTIAL                     61473
#define IDS_CONNECTING                  61474
#define IDS_MERGING                     61475
#define IDS_DOWNLOADCANRESUME           61476
#define IDS_DOWNLOADCANNOTRESUME        61477
#define IDS_COMPLETEDS                  61478
#define IDS_FORMAT1                     61479
#define IDS_FORMAT2                     61480
#define IDS_FORMAT3                     61481
#define IDS_INITIATE                    61482
#define IDS_REMOVE                      61483
#define IDS_TRAYTIP                     61484
#define IDS_ERRNOTE                     61485
#define IDS_INVALIDURL                  61486
#define IDS_URLACCESS                   61487
#define IDS_PARSE                       61488
#define IDS_REMOTE                      61489
#define IDS_GO                          61490
#define IDS_DEFAULTPATH                 61491
#define IDS_NOTE                        61492
#define IDS_TIP                         61493

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        183
#define _APS_NEXT_COMMAND_VALUE         32800
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
